
if (NOT WIN32)
    find_package (PkgConfig)
    if (PKG_CONFIG_FOUND)
        pkg_check_modules (LIBJANSSON QUIET jansson)
    endif (PKG_CONFIG_FOUND)
endif (NOT WIN32)

find_path (LIBJANSSON_INCLUDE_DIR jansson.h PATHS ${LIBJANSSON_INCLUDE_DIRS} ${WIN32_LIBAV_DIR}/include)
list (APPEND LIBJANSSON_INCLUDE_DIRS ${LIBJANSSON_INCLUDE_DIR})
find_library (LIBJANSSON_LIBRARY NAMES jansson HINTS ${LIBJANSSON_LIBDIR} ${LIBJANSSON_LIBRARY_DIRS} ${WIN32_LIBAV_DIR}/bin)
list (APPEND LIBJANSSON_LIBRARIES ${LIBJANSSON_LIBRARY})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args (LibJansson DEFAULT_MSG LIBJANSSON_LIBRARIES LIBJANSSON_INCLUDE_DIRS)
set (LIBJANSSON_FOUND ${LibJansson_FOUND})

if (LibJansson_FOUND)
    set (LIBJANSSON_LIBRARIES ${LIBJANSSON_LIBRARY})
endif (LibJansson_FOUND)

mark_as_advanced (LIBJANSSON_INCLUDE_DIRS LIBJANSSON_LIBRARIES)