
if (NOT WIN32)
    find_package (PkgConfig)
    if (PKG_CONFIG_FOUND)
        pkg_check_modules (LIBID3TAG QUIET id3tag)
    endif (PKG_CONFIG_FOUND)
endif (NOT WIN32)

find_path (LIBID3TAG_INCLUDE_DIR id3tag.h PATHS ${LIBID3TAG_INCLUDE_DIRS} ${WIN32_LIBAV_DIR}/include)
list (APPEND LIBID3TAG_INCLUDE_DIRS ${LIBID3TAG_INCLUDE_DIR})
find_library (LIBID3TAG_LIBRARY NAMES id3tag HINTS ${LIBID3TAG_LIBDIR} ${LIBID3TAG_LIBRARY_DIRS} ${WIN32_LIBAV_DIR}/bin)
list (APPEND LIBID3TAG_LIBRARIES ${LIBID3TAG_LIBRARY})

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args (LibId3Tag DEFAULT_MSG LIBID3TAG_LIBRARIES LIBID3TAG_INCLUDE_DIRS)
set (LIBID3TAG_FOUND ${LibId3Tag_FOUND})

if (LibId3Tag_FOUND)
    set (LIBID3TAG_LIBRARIES ${LIBID3TAG_LIBRARY})
endif (LibId3Tag_FOUND)

mark_as_advanced (LIBID3TAG_INCLUDE_DIRS LIBID3TAG_LIBRARIES)